config/routes.rb
Rails.application.routes.draw do
  root "whiskys#index"
  resources :whiskys do 
    resources :comments
  end
  resources :places, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :whisky
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/whisky.rb
class Whisky < ApplicationRecord
    has_many :comments
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @whisky = Whisky.find(params[:whisky_id])
        @comment = @whisky.comments.create(comment_params)
        redirect_to whisky_path(@whisky)
      end
    def destroy
      @whisky = Whisky.find(params[:whisky_id])
      @comment = @whisky.comments.find(params[:id])
      @comment.destroy
      redirect_to whisky_path(@whisky)
    end  
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    def index
        @places = Place.all
      end
      def load_places  
        @places_default = Gmaps4rails.build_markers(Place.all) do |plot, marker|  
           marker.lat plot.latitude  
           marker.lng plot.longitude  
     
           @status = rand(1..4)  
           @battery = rand(10..90)  
           @ip = "192.168."+rand(0..255).to_s+"."+rand(15..250).to_s  
           @connected = rand(50..100)  
     
           if @status == 1  
             url_alert = "/good.png"  
             @status == "Normal"  
           else  
             url_alert = "/alert.png"  
           end  
     
           marker.picture({  
             "url" => url_alert,  
             "width" => 35,  
             "height" => 30  
           })  
     
           marker.infowindow render_to_string(:partial => "/places/info",   
             :locals => {:name => plot.name, :battery => @battery, :date => rand(6.months.ago..Time.now), :ip => @ip, :connected => @connected })  
        end  
      end
     
     def index  
        load_places  
     
        @places = Place.all  
     end
end

app/controllers/whiskys_controller.rb
class WhiskysController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @whiskys = Whisky.all
  end
  def show
    @whiskys = Whisky.find(params[:id])
  end
  def new
    @whisky = Whisky.new
  end

  def create
    @whisky = Whisky.new(whisky_params)
    if @whisky.save
      redirect_to @whisky
    else
      render :new
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def whisky_params
    params.require(:whisky).permit(:title, :body)
  end
  
# class whisky_api
#   BASE_URL = 
#   API_PARTIAL_URL = 
#   def quary
#     request = HTTParty.get(BASE_URL+@search_format+API_PARTIAL_URL).to_json
#     @request_hash = JSON.parse(request)
#   end
  
#   def initialize(user_search_imput)
#     @search_format = ""
#   end
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/whiskys_helper.rb
module WhiskysHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.whisky, comment],
               method: :delete,
               data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @whiskys, @whiskys.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiskyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/whiskys/index.html.erb
<%= javascript_pack_tag 'hello_vue' %>

<h1>whiskys</h1>



<ul>
  <% @whiskys.each do |whisky| %>
    <li>
      <%= link_to whisky.title, whisky_path(whisky) %>
    </li>
  <% end %>
</ul>

<ul>
</ul>

<%= link_to "New whisky", new_whisky_path %>

app/views/whiskys/new.html.erb
<h1>New Whisky</h1>


<form action="/whiskys" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="...">

  <div>
    <label for="whisky_title">Title</label><br>
    <input type="text" name="whisky[title]" id="whisky_title">
  </div>

  <div>
    <label for="whisky_body">Body</label><br>
    <textarea name="whisky[body]" id="whisky_body"></textarea>
  </div>
  <div>
    <label for="whisky_age">age</label><br>
    <textarea name="whisky[age]" id="whisky_age"></textarea>
  </div>

  <div>
    <label for="whisky_region">region</label><br>
    <textarea name="whisky[region]" id="whisky_region"></textarea>
  </div>
  <div>
    <label for="whisky_ABV">ABV</label><br>
    <textarea name="whisky[ABV]" id="whisky_ABV"></textarea>
  </div>

  <div>
    <input type="submit" name="commit" value="Create Whisky" data-disable-with="Create Whisky">
  </div>
</form>
<div>

</div>

app/views/whiskys/show.html.erb
<h1><%= @whiskys.title %></h1>

<p><%= @whiskys.body %></p>

<h2>Comments</h2>
<%= render @whiskys.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "Back", whiskys_path %>